### ISSUE TITLE
Commenti al codice

### ISSUE THREAD

**Issue by mnarizzano** [mnarizzano/se20-project-16#1]
Il codice non segue le coding convetions descritte a lezione in particolare per i commenti alle classi e alle funzioni.
Inoltre ogni file dovrebbe avere un intestazione con chi è l'autore/i del file.
mn

**Comment by kyoumahououin** [comment]
The code has been commented according to Google's python code convention. While doing so many "one line comments" have been cleaned out and the free-license header (containing the names of the authors) has been added too.
